apiVersion: v1
kind: Service
metadata:
  name: captureorder
  namespace: aks-workshop-dev
spec:
  selector:
    app: captureorder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080    
  type: LoadBalancer