apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureorder
  namespace: aks-workshop-dev
spec:
  selector:
      matchLabels:
        app: captureorder
  replicas: 1
  template:
      metadata:
        labels:
            app: captureorder
      spec:
        containers:
        - name: captureorder
          image: akswkshpacr.azurecr.io/captureorder:v1.0.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:          
          - name: MONGOHOST
            valueFrom:
                secretKeyRef:
                  key: mongohost
                  name: aks-workshop-mongo-secret
          - name: MONGOUSER
            valueFrom:
                secretKeyRef:
                  key: mongouser
                  name: aks-workshop-mongo-secret
          - name: MONGOPASSWORD
            valueFrom:
                secretKeyRef:
                  key: mongopassword
                  name: aks-workshop-mongo-secret          
          ports:
          - containerPort: 8080
        imagePullSecrets:
          - name: aks-workshop-secret
        nodeSelector:
          agentpool: akswkpool