apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: captureorder
  namespace: aks-workshop-dev
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: captureorder
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 70  